export const SET_DATA_TYPE = 'SET_DATA_TYPE';
export const SET_DISPLAY_DATE = 'SET_DISPLAY_DATE';
export const TOGGLE_AUTO = 'TOGGLE_AUTO';
export const SET_SELECTED_BOROUGH = 'SET_SELECTED_BOROUGH';
export const RESET = 'RESET';
